### ISSUE TITLE
Expecting ES6 runtime to work?

### ISSUE THREAD

**Issue by cliren** [exogenesick/istanbul-coverage-slack#1]
I am getting the below error when following the instructions to run, can it compiled to es5?

` let parsedConfig;
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/surenrk/code/GoodreadsWebNodeModules/configuration/rails-root/node_modules/istanbul-coverage-slack/bin/shout.js:6:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)`

**Comment by cliren** [comment]
This is a great library, any chance that this question be addressed before proceeding to another solution?
